name: Génération Doc PDF Style Entreprise

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Télécharger le template Eisvogel
        run: |
          mkdir -p ~/.local/share/pandoc/templates
          wget https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/v2.4.0/eisvogel.tex -O ~/.local/share/pandoc/templates/eisvogel.latex

      - name: Générer le PDF avec Pandoc Officiel
        uses: docker://pandoc/extra:latest
        with:
          args: >-
            README.md
            --from markdown
            --template eisvogel
            --pdf-engine=xelatex
            --toc
            --toc-depth=3
            --number-sections
            -V titlepage=true
            -V titlepage-color="0F172A"
            -V titlepage-text-color="FFFFFF"
            -V titlepage-rule-color="0EA5E9"
            -V titlepage-rule-height=4
            -V header-right="CONFIDENTIEL"
            -V footer-right="Page \thepage"
            -o documentation.pdf

      - name: Publier le PDF en Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-PDF
          path: documentation.pdf