name: Export PDF

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilation du Markdown en PDF
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc wkhtmltopdf
          pandoc README.md -o documentation.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: Documentation-PDF
          path: documentation.pdf
