name: Export PDF

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code source
        uses: actions/checkout@v4

      - name: Installer Pandoc et WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint

      - name: Générer le PDF continu
        run: |
          pandoc README.md \
            --pdf-engine=weasyprint \
            --metadata title="Documentation Technique" \
            -o documentation.pdf

      - name: Publier le PDF en Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-PDF
          path: documentation.pdf